# Generated by Django 5.1.4 on 2025-01-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="League name, for example 'World Championship' or 'NHL'.", max_length=100)),
                ('sport', models.CharField(help_text="Type of sport, e.g., 'Hockey', 'Soccer'.", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of the league.', null=True)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Team name, for example 'Finland' or 'Canada'.", max_length=100)),
                ('abbreviation', models.CharField(help_text="Three-letter abbreviation for the team, for example 'FIN' or 'CAN'.", max_length=3)),
                ('logo', models.ImageField(blank=True, help_text='Team logo image.', null=True, upload_to='team_logos/')),
                ('country_iso', models.CharField(blank=True, help_text="Two-letter ISO Alpha-2 country code, for example 'FI' for Finland. Leave blank for non-national teams.", max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Season name, for example '2025 World Championship'.", max_length=100)),
                ('start_date', models.DateField(help_text='Start date of the season.')),
                ('end_date', models.DateField(help_text='End date of the season.')),
                ('visible', models.BooleanField(default=True, help_text='Indicates whether the season is visible in the UI.')),
                ('league', models.ForeignKey(help_text='The league to which this season belongs.', on_delete=django.db.models.deletion.CASCADE, to='scoreguru.league')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='TeamsInSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(help_text='The season in which the team is participating.', on_delete=django.db.models.deletion.CASCADE, to='scoreguru.season')),
                ('team', models.ForeignKey(help_text='The team participating in the season.', on_delete=django.db.models.deletion.CASCADE, to='scoreguru.team')),
            ],
            options={
                'verbose_name': 'Team in Season',
                'verbose_name_plural': 'Teams in Season',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.PositiveIntegerField(blank=True, help_text='Goals scored by the home team (leave blank if the game has not been played yet).', null=True)),
                ('visitor_goals', models.PositiveIntegerField(blank=True, help_text='Goals scored by the visitor team (leave blank if the game has not been played yet).', null=True)),
                ('start_datetime', models.DateTimeField(help_text='The date and time when the game is scheduled to start.')),
                ('season', models.ForeignKey(help_text='The season this game belongs to.', on_delete=django.db.models.deletion.CASCADE, to='scoreguru.season')),
                ('home_team', models.ForeignKey(help_text='The home team participating in the game.', on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='scoreguru.teamsinseason')),
                ('visitor_team', models.ForeignKey(help_text='The visitor team participating in the game.', on_delete=django.db.models.deletion.CASCADE, related_name='visitor_games', to='scoreguru.teamsinseason')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_home_goals', models.PositiveIntegerField(help_text='Predicted goals for the home team.')),
                ('predicted_visitor_goals', models.PositiveIntegerField(help_text='Predicted goals for the visitor team.')),
                ('correct_home_goals', models.PositiveIntegerField(default=0, help_text='Correct predictions for home team goals.')),
                ('correct_visitor_goals', models.PositiveIntegerField(default=0, help_text='Correct predictions for visitor team goals.')),
                ('correct_winner', models.PositiveIntegerField(default=0, help_text='Correct predictions for the winner.')),
                ('correct_tie', models.PositiveIntegerField(default=0, help_text='Correct predictions for ties.')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='The total points earned by the user in this season.')),
                ('game', models.ForeignKey(help_text='The game being predicted.', on_delete=django.db.models.deletion.CASCADE, to='scoreguru.game')),
                ('user', models.ForeignKey(help_text='The user who made the prediction.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_home_goals', models.PositiveIntegerField(default=0, help_text='Correct predictions for home team goals.')),
                ('correct_visitor_goals', models.PositiveIntegerField(default=0, help_text='Correct predictions for visitor team goals.')),
                ('correct_winner', models.PositiveIntegerField(default=0, help_text='Correct predictions for the winner.')),
                ('correct_tie', models.PositiveIntegerField(default=0, help_text='Correct predictions for ties.')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='The total points earned by the user in this season.')),
                ('user', models.ForeignKey(help_text='The user whose score is being tracked.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(help_text='The season for which the scoreboard entry is valid.', on_delete=django.db.models.deletion.CASCADE, to='scoreguru.season')),
            ],
            options={
                'verbose_name': 'Scoreboard',
                'verbose_name_plural': 'Scoreboards',
                'unique_together': {('user', 'season')},
            },
        ),
        migrations.AddConstraint(
            model_name='teamsinseason',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='unique_team_in_season'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('season', 'home_team', 'visitor_team', 'start_datetime')},
        ),
    ]
